### ISSUE TITLE
Buster support

### ISSUE THREAD

**Issue by mjfwalsh** [mjfwalsh/omxplayer#1]
I'm afraid I'd forgotten that you have to enable issues pages.

Buster had also completely passed me by, and I hadn't noticed that more recent releases of omxplayer use apt packages instead of distributing its own custom libraries.

prepare-native-raspbian.sh now covers both Stretch and Buster dependancies, as well as the different packages required for the different compile methods.

This is still experimental software and I can't guarantee it will compile or run, but I have compiled it on both Stretch and Buster on my rpi3.

**Comment by dont32** [comment]
Good performance. But I build in raspberry pi 3 . After some minute app is stopped but process is still running 
@mjfwalsh Do you have any suggestion ? Thanks

**Comment by dont32** [comment]
@mjfwalsh Can you provide raspbian os date version  ?

**Comment by mjfwalsh** [comment]
I build on Raspberry 3 too, Model B, currently running Buster, release 10. It should also work on Stretch but it's been a while since I tested it.

Could you upload your terminal output?

**Comment by dont32** [comment]
It's just print "omxplayer is stopped" , video is stopped but i checked process with command "ps -aux | grep omxplayer" is existed.
i check log is normal. Os system is newest buster

**Comment by dont32** [comment]
It's refer to this issue https://github.com/popcornmix/omxplayer/issues/798

**Comment by mjfwalsh** [comment]
"Stopped" is just what bash prints out when you suspend a process by pressing Ctrl-Z. It has nothing to do with omxplayer.

**Comment by mjfwalsh** [comment]
Closing as Buster is my main development platform now.
