### ISSUE TITLE
Disabling OSD

### ISSUE THREAD

**Issue by dirtpi** [mjfwalsh/omxplayer#5]
Thanks for you work on this.  Now that the OSD is generated a different way in order to work with Rasp Bullseye, how can you disable it?   --no-osd no longer works.

Thanks

**Comment by mjfwalsh** [comment]
It works for me. Are you using my latest version?

**Comment by dirtpi** [comment]
I did a fresh install and it's working now.  I had originally installed the standard OMXplayer and then overwrote the files with yours and it had some issues.  I really love the position remembering feature!  Great work, my friend.  It's a shame they deprecated OMXplayer as it really is the best imo.
